name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permette di avviare la build manualmente da GitHub

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installazione dipendenze
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK come Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aimodrive-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
